project:
  type: book
  output-dir: _book
  
book:
  title: "Bynatur Atlas"
  author: "Maria Korkou"
  description: | 
    Add some description here if you like.
  repo-url: https://mariakork.github.io/Test_book/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - part: my-first-book.qmd
      chapters: 
        - hello-world.qmd
  appendices:
    - appendix-notes.qmd
    
format:
  html: 
    theme: 
    - cosmo
    - NINAstyle.scss
    
    code-link: true

bibliography: references.bib
csl: NINArefStyle.csl
